name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongo: ["4.2", "4.4", "5.0", "6.0", "latest"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongo }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install tools
        run: |
          git clone https://github.com/mongodb/mongo-tools --depth=1
          cd mongo-tools/mongoimport/main;go build -o mongoimport;mv mongoimport /usr/bin

      - name: Prepare data files
        run: cat foo_bar.dumps | mongoimport --host="127.0.0.1" --port="27017" --db="foo" --collection="bar"
